name: AdminPanel CD

# Project templates come equipped with CI/CD for both Azure DevOps and GitHub, providing you with a hassle-free way to get started with your new project. It is important to note that you should not depend on the contents of this file. More info at https://bitplatform.dev/admin-panel/dev-ops

env:
  WEB_APP_DEPLOYMENT_TYPE: 'DefaultDeploymentType'
  API_SERVER_ADDRESS: 'https://adminpanel.bitplatform.dev/api/'
  APP_SERVICE_NAME: 'app-service-ad-test'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build_blazor_api_wasm:
    name: build blazor api + web assembly
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/Templates/AdminPanel/Bit.AdminPanel/src/global.json

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Switch to blazor web assembly
      run:  sed -i 's/Microsoft.NET.Sdk.Web/Microsoft.NET.Sdk.BlazorWebAssembly/g' src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Web/AdminPanel.Client.Web.csproj

    - name: Restore workloads
      run: dotnet workload restore src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Web/AdminPanel.Client.Web.csproj -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}"

    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
      
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Server/Api/AdminPanel.Server.Api.csproj -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}" -p:Configuration=Release -p:MultilingualEnabled=true

    - name: Publish
      run: dotnet publish src/Templates/AdminPanel/Bit.AdminPanel/src/Server/Api/AdminPanel.Server.Api.csproj -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}" -p:Configuration=Release -p:MultilingualEnabled=true --self-contained -r linux-x64 -o ${{env.DOTNET_ROOT}}/api-web

    - name: Upload api-web artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-web-bundle
        path: ${{env.DOTNET_ROOT}}/api-web

  deploy_blazor_api_wasm:
    name: deploy blazor api + web assembly
    needs: build_blazor_api_wasm
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Retrieve api-web bundle
        uses: actions/download-artifact@v2
        with:
          name: api-web-bundle

      - name: Delete IdentityCertificate.pfx
        run: |
            rm IdentityCertificate.pfx

      - name: Extract identity certificate from env
        uses: timheuer/base64-to-file@v1
        with:
            fileDir: './'
            fileName: 'IdentityCertificate.pfx'
            encodedString: ${{ secrets.API_IDENTITY_CERTIFICATE_FILE_BASE64 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.ADMINPANEL_AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: .

  build_blazor_hybrid_windows:
    name: build blazor hybrid (windows)
    runs-on: windows-latest
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@v3
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/Templates/AdminPanel/Bit.AdminPanel/src/global.json
  
    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
  
    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-windows10.0.19041.0
  
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true -p:GenerateAppxPackageOnBuild=false -p:RuntimeIdentifier=win10-x86 -p:MultilingualEnabled=true -f net7.0-windows10.0.19041.0
  
    - name: Build exe
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true -p:GenerateAppxPackageOnBuild=false -p:RuntimeIdentifier=win10-x86 -p:MultilingualEnabled=true -p:ApplicationDisplayVersion="$Application_Display_Version" -p:ApplicationVersion="$Application_Version" -f net7.0-windows10.0.19041.0
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-exe-bundle
        path: src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/bin/release/net7.0-windows10.0.19041.0/win10-x86
  
  build_blazor_hybrid_android:
    name: build blazor hybrid (android)
    runs-on: windows-latest
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@v3
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/Templates/AdminPanel/Bit.AdminPanel/src/global.json
  
    - name: Extract Android signing key from env
      uses: timheuer/base64-to-file@v1
      with:
          fileDir: './src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/'
          fileName: 'AdminPanel.keystore'
          encodedString: ${{ secrets.ANDROID_RELEASE_KEYSTORE_FILE_BASE64 }}
  
    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
  
    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-android
  
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:RunAOTCompilation=false -p:MultilingualEnabled=true -f net7.0-android
  
    - name: Build aab
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="AdminPanel.keystore" -p:AndroidSigningKeyAlias=bitplatform -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -p:MultilingualEnabled=true -p:ApplicationDisplayVersion="$Application_Display_Version" -p:ApplicationVersion="$Application_Version" -f net7.0-android
  
    - name: Build apk
      run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="AdminPanel.keystore" -p:AndroidSigningKeyAlias=bitplatform -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -p:MultilingualEnabled=true -p:ApplicationDisplayVersion="$Application_Display_Version" -p:ApplicationVersion="$Application_Version" -f net7.0-android
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-bundle
        path: src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/bin/release/net7.0-android/*-Signed.*
  
  build_blazor_hybrid_maccatalyst:
     name: build blazor hybrid (maccatalyst)
     runs-on: macos-latest
   
     steps:
      
     - name: Checkout source code
       uses: actions/checkout@v3
      
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         global-json-file: src/Templates/AdminPanel/Bit.AdminPanel/src/global.json
   
     - name: Update appsettings.json api server address
       uses: microsoft/variable-substitution@v1 
       with:
         files: 'src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Shared/appsettings.json'
       env:
         ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
   
     - name: Restore workloads
       run: dotnet workload restore src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-maccatalyst
   
     - name: Build (To generate CSS/JS files)
       run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:CreatePackage=true -p:MultilingualEnabled=true -f net7.0-maccatalyst
   
     - name: Build pkg
       run: dotnet build src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/AdminPanel.Client.App.csproj -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:CreatePackage=true -p:MultilingualEnabled=true -p:ApplicationDisplayVersion="$Application_Display_Version" -p:ApplicationVersion="$Application_Version" -f net7.0-maccatalyst
   
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: mac-pkg-bundle
         path: src/Templates/AdminPanel/Bit.AdminPanel/src/Client/App/bin/release/net7.0-maccatalyst/*.pkg