name: BlazorUI Nuget Package
on:
  workflow_dispatch:
    push:
        branches:
        - develop
        paths:
        - 'src/Client/Web/Bit.Client.Web.BlazorUI/**'
jobs:
  build:
    name: build / deploy nuget package
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Client/Web/Bit.Client.Web.BlazorUI/Bit.Client.Web.BlazorUI.csproj
    - name: dotnet build
      run: dotnet msbuild src/Client/Web/Bit.Client.Web.BlazorUI/Bit.Client.Web.BlazorUI.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet build
      run: dotnet msbuild src/Client/Web/Bit.Client.Web.BlazorUI/Bit.Client.Web.BlazorUI.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack
      run: dotnet msbuild src/Client/Web/Bit.Client.Web.BlazorUI/Bit.Client.Web.BlazorUI.csproj /T:pack /P:Configuration=Release
    - name: dotnet nuget push
      run: dotnet nuget push src/Client/Web/Bit.Client.Web.BlazorUI/bin/Release/*.nupkg --source https://nuget.pkg.github.com/bitfoundation/index.json --api-key ${{secrets.PACKAGE_API_KEY}}
