name: bit platform CI - ResxTranslator

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'src/ResxTranslator/**'

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

jobs:
  build-ResxTranslator:
    if: startsWith(github.event.pull_request.title, 'Prerelease') != true && startsWith(github.event.pull_request.title, 'Release') != true && startsWith(github.event.pull_request.title, 'Version') != true
    name: build Bit.ResxTranslator
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
        
    - name: dotnet build
      run: dotnet build src/ResxTranslator/Bit.ResxTranslator.slnx
