name: BlazorUI CI
on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'src/Client/Web/**'
jobs:
  build:
    name: build and test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Bit.Client.Web.BlazorUI-CI.sln
    - name: Build
      run: dotnet build --no-restore src/Bit.Client.Web.BlazorUI-CI.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Bit.Client.Web.BlazorUI.Tests.csproj
