name: Bit Platform CI
on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'src/**'
jobs:
  build-prerelease:
    if: startsWith(github.event.pull_request.title, 'Prerelease') || startsWith(github.event.pull_request.title, 'Release')
    name: build and test for prerelease
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore prerelease
      run: dotnet restore src/Bit-CI-prerelease.sln
    - name: MSBuild prerelease
      run: dotnet msbuild src/Bit-CI-prerelease.sln -m:1
    - name: Test
      run: dotnet test --no-build --verbosity normal src/BlazorUI/Bit.BlazorUI.Tests/Bit.BlazorUI.Tests.csproj
  build:
    if: startsWith(github.event.pull_request.title, 'Prerelease') != true && startsWith(github.event.pull_request.title, 'Release') != true
    name: build and test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore src/Bit-CI.sln
    - name: MSBuild
      run: dotnet msbuild src/Bit-CI.sln -m:1
    - name: Test
      run: dotnet test --no-build --verbosity normal src/BlazorUI/Bit.BlazorUI.Tests/Bit.BlazorUI.Tests.csproj
