name: bit platform CI - CodeAnalyzers

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'src/CodeAnalyzers/**'

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

jobs:
  build:
    name: build Bit.CodeAnalyzers
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: src/global.json

    - name: dotnet build
      run: dotnet build src/CodeAnalyzers/Bit.CodeAnalyzers.slnx
