name: Blazor UI Demo CD

# Project templates come equipped with CI/CD for both Azure DevOps and GitHub, providing you with a hassle-free way to get started with your new project. It is important to note that you should not depend on the contents of this file. More info at https://bitplatform.dev/admin-panel/dev-ops

env:
  WEB_APP_DEPLOYMENT_TYPE: 'SSR'
  API_SERVER_ADDRESS: 'https://components.bitplatform.dev/api/'
  APP_SERVICE_NAME: 'bitcomponents'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build_blazor_api_wasm:
    name: build blazor api + web assembly
    runs-on: windows-latest

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/BlazorUI/Demo/global.json

    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Switch to blazor web assembly
      run:  sed -i 's/Microsoft.NET.Sdk.Web/Microsoft.NET.Sdk.BlazorWebAssembly/g' src/BlazorUI/Demo/Client/Web/Bit.BlazorUI.Demo.Client.Web.csproj

    - name: Switch to blazor web assembly
      shell: pwsh
      run: (Get-Content src/BlazorUI/Demo/Client/Web/Bit.BlazorUI.Demo.Client.Web.csproj) -replace 'Microsoft.NET.Sdk.Web', 'Microsoft.NET.Sdk.BlazorWebAssembly' | Set-Content src/BlazorUI/Demo/Client/Web/Bit.BlazorUI.Demo.Client.Web.csproj

    - name: Restore workloads
      run: dotnet workload restore src/BlazorUI/Demo/Client/Web/Bit.BlazorUI.Demo.Client.Web.csproj -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}"

    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/BlazorUI/Demo/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: 'api/'
      
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/BlazorUI/Demo/Server/Api/Bit.BlazorUI.Demo.Server.Api.csproj -m:1 -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}" -p:Configuration=Release

    - name: Publish
      run: dotnet publish src/BlazorUI/Demo/Server/Api/Bit.BlazorUI.Demo.Server.Api.csproj -m:1 -p:BlazorMode=BlazorWebAssembly -p:WebAppDeploymentType="${{ env.WEB_APP_DEPLOYMENT_TYPE }}" -p:Configuration=Release --self-contained -r linux-x64 -o api-web

    - name: Upload api-web artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-web-bundle
        path: src/BlazorUI/Demo/Server/Api/api-web

  deploy_blazor_api_wasm:
    name: deploy blazor api + web assembly
    needs: build_blazor_api_wasm
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Retrieve api-web bundle
        uses: actions/download-artifact@v2
        with:
          name: api-web-bundle

      - name: Delete IdentityCertificate.pfx
        run: |
            rm IdentityCertificate.pfx

      - name: Extract identity certificate from env
        uses: timheuer/base64-to-file@v1
        with:
            fileDir: './'
            fileName: 'IdentityCertificate.pfx'
            encodedString: ${{ secrets.API_IDENTITY_CERTIFICATE_FILE_BASE64 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.COMPONENTS_AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: .

  build_blazor_hybrid_windows:
    name: build blazor hybrid (windows)
    runs-on: windows-latest
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@v3
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/BlazorUI/Demo/global.json
  
    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/BlazorUI/Demo/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
  
    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-windows10.0.19041.0
  
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -m:1 -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true -p:GenerateAppxPackageOnBuild=false -p:RuntimeIdentifier=win10-x86 -f net7.0-windows10.0.19041.0
  
    - name: Build exe
      run: dotnet build src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -m:1 -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true -p:GenerateAppxPackageOnBuild=false -p:RuntimeIdentifier=win10-x86 -p:ApplicationDisplayVersion="${{ vars.APPLICATION_DISPLAY_VERSION }}" -p:ApplicationVersion="${{ vars.APPLICATION_VERSION }}" -f net7.0-windows10.0.19041.0
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win-exe-bundle
        path: src/BlazorUI/Demo/Client/App/bin/release/net7.0-windows10.0.19041.0/win10-x86
  
  build_blazor_hybrid_android:
    name: build blazor hybrid (android)
    runs-on: windows-latest
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@v3
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/BlazorUI/Demo/global.json
  
    - name: Extract Android signing key from env
      uses: timheuer/base64-to-file@v1
      with:
          fileDir: './src/BlazorUI/Demo/Client/App/'
          fileName: 'BitBlazorUIDemo.keystore'
          encodedString: ${{ secrets.ANDROID_RELEASE_KEYSTORE_FILE_BASE64 }}
  
    - name: Update appsettings.json api server address
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'src/BlazorUI/Demo/Client/Shared/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
  
    - name: Install Maui
      run: dotnet workload install maui

    - name: Restore workloads
      run: dotnet workload restore src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -p:BlazorMode=BlazorHybrid -f net7.0-android
  
    - name: Build (To generate CSS/JS files)
      run: dotnet build src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -m:1 -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:RunAOTCompilation=false -f net7.0-android
  
    - name: Build aab
      run: dotnet build src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -m:1 -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="BitBlazorUIDemo.keystore" -p:AndroidSigningKeyAlias=bitplatform -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -p:ApplicationDisplayVersion="${{ vars.APPLICATION_DISPLAY_VERSION }}" -p:ApplicationVersion="${{ vars.APPLICATION_VERSION }}" -f net7.0-android
  
    - name: Build apk
      run: dotnet build src/BlazorUI/Demo/Client/App/Bit.BlazorUI.Demo.Client.App.csproj -m:1 -p:BlazorMode=BlazorHybrid -p:Configuration=Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="BitBlazorUIDemo.keystore" -p:AndroidSigningKeyAlias=bitplatform -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -p:ApplicationDisplayVersion="${{ vars.APPLICATION_DISPLAY_VERSION }}" -p:ApplicationVersion="${{ vars.APPLICATION_VERSION }}" -f net7.0-android
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-bundle
        path: src/BlazorUI/Demo/Client/App/bin/release/net7.0-android/*-Signed.*