name: Prerelease nuget packages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v-*'

jobs:
  build-publish:
    name: build & publish
    runs-on: windows-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: dotnet restore BlazorUI
      run: dotnet restore src/BlazorUI/Bit.BlazorUI/Bit.BlazorUI.csproj
    - name: dotnet msbuild BlazorUI (1)
      run: dotnet msbuild src/BlazorUI/Bit.BlazorUI/Bit.BlazorUI.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet msbuild BlazorUI (2)
      run: dotnet msbuild src/BlazorUI/Bit.BlazorUI/Bit.BlazorUI.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack BlazorUI
      run: dotnet pack src/BlazorUI/Bit.BlazorUI/Bit.BlazorUI.csproj --output . --configuration Release
      
    - name: dotnet restore Bswup
      run: dotnet restore src/Bswup/Bit.Bswup/Bit.Tooling.Bswup.csproj
    - name: dotnet msbuild Bswup (1)
      run: dotnet msbuild src/Bswup/Bit.Bswup/Bit.Tooling.Bswup.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet msbuild Bswup (2)
      run: dotnet msbuild src/Bswup/Bit.Bswup/Bit.Tooling.Bswup.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack Bswup
      run: dotnet pack src/Bswup/Bit.Bswup/Bit.Tooling.Bswup.csproj --output . --configuration Release
            
    - name: dotnet restore CodeAnalyzer
      run: dotnet restore src/Tooling/Bit.Tooling.CodeAnalyzer/Bit.Tooling.CodeAnalyzer.csproj
    - name: dotnet msbuild CodeAnalyzer
      run: dotnet msbuild src/Tooling/Bit.Tooling.CodeAnalyzer/Bit.Tooling.CodeAnalyzer.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack CodeAnalyzer
      run: dotnet pack src/Tooling/Bit.Tooling.CodeAnalyzer/Bit.Tooling.CodeAnalyzer.csproj --output . --configuration Release
      
    - name: dotnet restore SourceGenerators
      run: dotnet restore src/Tooling/Bit.Tooling.SourceGenerators/Bit.Tooling.SourceGenerators.csproj
    - name: dotnet msbuild SourceGenerators
      run: dotnet msbuild src/Tooling/Bit.Tooling.SourceGenerators/Bit.Tooling.SourceGenerators.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack SourceGenerators
      run: dotnet pack src/Tooling/Bit.Tooling.SourceGenerators/Bit.Tooling.SourceGenerators.csproj --output . --configuration Release

    - name: dotnet pack TodoTemplate
      run: dotnet pack src/Templates/TodoTemplate/Bit.TodoTemplate.ProjectTemplate.csproj --output . --configuration Release
      
    - name: dotnet restore Butil
      run: dotnet restore src/Butil/Bit.Butil/Bit.Tooling.Butil.csproj
    - name: dotnet msbuild Butil (1)
      run: dotnet msbuild src/Butil/Bit.Butil/Bit.Tooling.Butil.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet msbuild Butil (2)
      run: dotnet msbuild src/Butil/Bit.Butil/Bit.Tooling.Butil.csproj /P:Configuration=Release /p:GeneratePackageOnBuild=false
    - name: dotnet pack Butil
      run: dotnet pack src/Butil/Bit.Butil/Bit.Tooling.Butil.csproj --output . --configuration Release
      
    - name: dotnet nuget push
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_API_KEY}}